<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="1480--CNM--GGN" failures="6" tests="14" name="restassuredtests" time="19.408" errors="0" timestamp="2022-07-24T16:59:32 IST">
  <testcase classname="com.restassuredautomation.testcases.TC005_DELETE_Employee" name="@BeforeClass deleteEmployee" time="0.001">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at com.restassuredautomation.testcases.TC005_DELETE_Employee.deleteEmployee(TC005_DELETE_Employee.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
... 30 more
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeClass deleteEmployee -->
  <testcase classname="com.restassuredautomation.testcases.TC005_DELETE_Employee" name="@AfterClass tearDown" time="-1.658662172218E9">
    <skipped/>
  </testcase> <!-- @AfterClass tearDown -->
  <testcase classname="com.restassuredautomation.testcases.TC001_GET_AllEmployee" name="checkContaintType" time="0.007"/>
  <testcase classname="com.restassuredautomation.testcases.TC001_GET_AllEmployee" name="checkCookies" time="0.0"/>
  <testcase classname="com.restassuredautomation.testcases.TC001_GET_AllEmployee" name="checkResponseBody" time="0.019"/>
  <testcase classname="com.restassuredautomation.testcases.TC001_GET_AllEmployee" name="checkResponseCode" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [200] but found [429]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [429]
at com.restassuredautomation.testcases.TC001_GET_AllEmployee.checkResponseCode(TC001_GET_AllEmployee.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- checkResponseCode -->
  <testcase classname="com.restassuredautomation.testcases.TC001_GET_AllEmployee" name="checkResponseTime" time="0.001"/>
  <testcase classname="com.restassuredautomation.testcases.TC001_GET_AllEmployee" name="getStatusLine" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]">
      <![CDATA[java.lang.AssertionError: expected [HTTP/1.1 200 OK] but found [HTTP/1.1 429 Too Many Requests]
at com.restassuredautomation.testcases.TC001_GET_AllEmployee.getStatusLine(TC001_GET_AllEmployee.java:75)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- getStatusLine -->
  <testcase classname="com.restassuredautomation.testcases.TC002_GET_Single_Employee_Data" name="checkResponseBody" time="0.004"/>
  <testcase classname="com.restassuredautomation.testcases.TC002_GET_Single_Employee_Data" name="checkResponseCode" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [200] but found [429]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [429]
at com.restassuredautomation.testcases.TC002_GET_Single_Employee_Data.checkResponseCode(TC002_GET_Single_Employee_Data.java:33)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- checkResponseCode -->
  <testcase classname="com.restassuredautomation.testcases.TC003_POST_Create_Employee" name="checkResponseBody" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [true] but found [{&amp;quot;status&amp;quot;:&amp;quot;success&amp;quot;,&amp;quot;data&amp;quot;:{&amp;quot;name&amp;quot;:&amp;quot;Johnu&amp;quot;,&amp;quot;salary&amp;quot;:&amp;quot;yvyzk&amp;quot;,&amp;quot;age&amp;quot;:&amp;quot;LR&amp;quot;,&amp;quot;id&amp;quot;:5916},&amp;quot;message&amp;quot;:&amp;quot;Successfully! Record has been added.&amp;quot;}Johnu]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [{"status":"success","data":{"name":"Johnu","salary":"yvyzk","age":"LR","id":5916},"message":"Successfully! Record has been added."}Johnu]
at com.restassuredautomation.testcases.TC003_POST_Create_Employee.checkResponseBody(TC003_POST_Create_Employee.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- checkResponseBody -->
  <testcase classname="com.restassuredautomation.testcases.TC003_POST_Create_Employee" name="checkStatusCode" time="0.0"/>
  <testcase classname="com.restassuredautomation.testcases.TC004_PUT_UpdateEmployee" name="checkResponseBody" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [&amp;lt;!DOCTYPE html&amp;gt;
&amp;lt;html&amp;gt;
&amp;lt;head&amp;gt;
    &amp;lt;meta charset=&amp;quot;UTF-8&amp;quot; /&amp;gt;
    &amp;lt;meta name=&amp;quot;robots&amp;quot; content=&amp;quot;noindex,nofollow,noarchive&amp;quot; /&amp;gt;
    &amp;lt;title&amp;gt;An Error Occurred: Method Not Allowed&amp;lt;/title&amp;gt;
    &amp;lt;style&amp;gt;body { background-color: #fff; color: #222; font: 16px/1.5 -apple-system, BlinkMacSystemFont, &amp;quot;Segoe UI&amp;quot;, Roboto, &amp;quot;Helvetica Neue&amp;quot;, Arial, sans-serif; margin: 0; }
.container { margin: 30px; max-width: 600px; }
h1 { color: #dc3545; font-size: 24px; }
h2 { font-size: 18px; }&amp;lt;/style&amp;gt;
&amp;lt;/head&amp;gt;
&amp;lt;body&amp;gt;
&amp;lt;div class=&amp;quot;container&amp;quot;&amp;gt;
    &amp;lt;h1&amp;gt;Oops! An Error Occurred&amp;lt;/h1&amp;gt;
    &amp;lt;h2&amp;gt;The server returned a &amp;quot;405 Method Not Allowed&amp;quot;.&amp;lt;/h2&amp;gt;

    &amp;lt;p&amp;gt;
        Something is broken. Please let us know what you were doing when this error occurred.
        We will fix it as soon as possible. Sorry for any inconvenience caused.
    &amp;lt;/p&amp;gt;
&amp;lt;/div&amp;gt;
&amp;lt;/body&amp;gt;
&amp;lt;/html&amp;gt;JohnS]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta name="robots" content="noindex,nofollow,noarchive" />
    <title>An Error Occurred: Method Not Allowed</title>
    <style>body { background-color: #fff; color: #222; font: 16px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; margin: 0; }
.container { margin: 30px; max-width: 600px; }
h1 { color: #dc3545; font-size: 24px; }
h2 { font-size: 18px; }</style>
</head>
<body>
<div class="container">
    <h1>Oops! An Error Occurred</h1>
    <h2>The server returned a "405 Method Not Allowed".</h2>

    <p>
        Something is broken. Please let us know what you were doing when this error occurred.
        We will fix it as soon as possible. Sorry for any inconvenience caused.
    </p>
</div>
</body>
</html>JohnS]
at com.restassuredautomation.testcases.TC004_PUT_UpdateEmployee.checkResponseBody(TC004_PUT_UpdateEmployee.java:61)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- checkResponseBody -->
  <testcase classname="com.restassuredautomation.testcases.TC004_PUT_UpdateEmployee" name="checkStatusCode" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [200] but found [405]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [405]
at com.restassuredautomation.testcases.TC004_PUT_UpdateEmployee.checkStatusCode(TC004_PUT_UpdateEmployee.java:72)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- checkStatusCode -->
  <testcase classname="com.restassuredautomation.testcases.TC005_DELETE_Employee" name="checkResponseBody" time="0.0">
    <skipped/>
  </testcase> <!-- checkResponseBody -->
  <testcase classname="com.restassuredautomation.testcases.TC005_DELETE_Employee" name="checkStatusCode" time="0.0">
    <skipped/>
  </testcase> <!-- checkStatusCode -->
</testsuite> <!-- restassuredtests -->
